spring:
  application:
    name: raon-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
